### ISSUE TITLE
Add documentation for from-scratch training as well as fine-tuning

### ISSUE THREAD

**Issue by TechnikEmpire** [TechnikEmpire/NsfwSqueezenet#2]

**Comment by TechnikEmpire** [comment]
Nope.

**Comment by rstml** [comment]
Not asking for the whole training/tuning doc, but can you please provide a bit more information about data used for training? Is it some well known data set like [this one](https://sites.google.com/site/pornographydatabase/)?

**Comment by TechnikEmpire** [comment]
No. One of the toughest parts about this was safely building training data. Its extremely dangerous to just pull down arbitrary images because who knows what you're getting. Initially I thought to use things like Tumblr scraping tools on adult Tumblr pages but thought better of it.

If you want to be sure that you're obtaining legal content, simply obtain movies from pornography companies that are well known and then use ffmpeg to extract every N frames to an image.

By doing this, you avoid ever coming across any sort of illegal pornography.

Once you extract frames you can use a well know classifier (Yahoo's model, now this one too), to filter the extracted images and remove all non-pornographic frames.

For negative images, Google has a huge CSV file you can download (gigs and gigs of links) where you can pull down random images.

From there you can follow any old tutorial on building those images into LMBD files and train away.

What might be interesting is to do what Yahoo did in their blog post. They didn't train from scratch like me. They took a pretrained imagenet model and transferred learning into a two class output with adult training data only. 

All the best. Let me know if you need anymore info. I'm not trying to hold back any trade secrets by closing this ticket or anything, I just didn't feel like writing that all out at the time.

**Comment by TechnikEmpire** [comment]
You can find commands like this:

https://superuser.com/questions/391257/extracting-one-of-every-10-frames-in-a-video-using-vlc-or-ffmpeg

I'd recommend every 200 frames or so personally. The content is too repetitive with a low interval.

**Comment by TechnikEmpire** [comment]
I've actually just tried hacking out some python to merge the weights and biases from the positive side of my network with all of imagenet pretrained with squeezenet. It's not quite what Yahoo did but maybe this will yield better results (not sure a narrow margin). Will post back with test results and if they are good, I will post the hybrid model here under squeenets license.
