### ISSUE TITLE
Example using the model

### ISSUE THREAD

**Issue by clmns** [TechnikEmpire/NsfwSqueezenet#3]
Awesome work @TechnikEmpire!

Do you maybe have an example how to use the model like classify.py in yahoos repo?

Thank you!

**Comment by TechnikEmpire** [comment]
@clmns I don't do python, but you can see me using the model, and yahoo's model, here:

https://github.com/TechnikEmpire/NsfwNET

It's a .NET library that's on Nuget.

There's C++ under the hood though. Example:

https://github.com/TechnikEmpire/NsfwNET/blob/master/NsfwNetNative/NsfwNetNative/SqueezenetClassifier.cpp

With this model, the recommended cutoff is between `.87D` and `.9999D`. Hardcore stuff is going to always hit `~1.0` on a positive detection. Plain nudity may register slightly lower than that.

**Comment by TechnikEmpire** [comment]
The cutoff is very narrow on this model compared to Yahoo's model. I figure that's because they trained their models by taking a 1000 class model and then re-training it. My model was from scratch. You need to tune the cutoff much more precisely in this case.
