### ISSUE TITLE
model usage

### ISSUE THREAD

**Issue by chen849157649** [TechnikEmpire/NsfwSqueezenet#4]
hi! How to use your model？
Do you have a complete demo?
Thank you very much!

**Comment by wormuz** [comment]
Same question here

**Comment by TechnikEmpire** [comment]
https://github.com/TechnikEmpire/NsfwNET

**Comment by TechnikEmpire** [comment]
If you use .net, there's a nuget package:
https://www.nuget.org/packages/NsfwNET/
