### ISSUE TITLE
Optimal rig for performance.

### ISSUE THREAD

**Issue by lxknvlk** [TechnikEmpire/NsfwSqueezenet#7]
I have tested this model by running on AWS ec2 instances. with cpu-only caffe c5.large i got around ~700ms processing time. 

Then i tried with the deep learning GPU instances with caffe-gpu, p3.2xlarge with the monstrous Tesla V100 and it did process in ~2700ms. 

What is the matter here? I was expecting to see a huge improvement in performance, i suppose less that 200ms for processing the image. What am i missing?

**Comment by TechnikEmpire** [comment]
Not all inference engines are created equal. This model executes in less than 40 milliseconds for me on a netbook using opencv dnn.

Use a difference inference engine.

**Comment by lxknvlk** [comment]
Hello @TechnikEmpire ! You have written in the README that "On modern hardware, I can run classification with this model at ~3msec on the CPU, including preprocessing.". Well i could get only 700ms execution time on a decent hardware.

I am using opencv 3.0, caffe and pycaffe. Please point me in the correct direction.

update: i have made some improvements to my code and fixed and enabled gpu on my configuration and now i get a ~350ms processing time. Still your's 3ms is far away.

**Comment by TechnikEmpire** [comment]
Compile opencv with the very latest sources and enable Intel inference engine in compilation. It will be used as the default inference engine. It supports 64 bit only.

Also you need to compile opencv with libjpeg-turbo static. Jpeg decoding takes longer than the network forward pass without doing this.

Its a lot of custom compilation. I further modified my build to enable openmp but to link to Microsoft's runtime instead of Intel's.

Hope this helps. You don't get this speed easily.

**Comment by TechnikEmpire** [comment]
Also python is garbage so its probably adding a lot of overhead here too.

**Comment by lxknvlk** [comment]
Thank you very much, i can investigate now.

 I got this advice from reddit "Caffe doesn't do a great job of optimizing runtime (inference) on GPUs. You should try to use TensorRT if you're on an nvidia GPU."

What do you think about this?

**Comment by TechnikEmpire** [comment]
I think they may have a point regarding caffe and optimisation but I disagree 100% with using anything proprietary here.

**Comment by TechnikEmpire** [comment]
Intel's inference engine has a model optimisation tool that does ahead of time layer fusion but opencv dnn also does this at runtime. The "optimized" model (made with Intel's tool) actually runs slower.

**Comment by jessetrana** [comment]
Do you think this is something that could be Dockerized well or is there too much arch-specific stuff in there?

**Comment by TechnikEmpire** [comment]
No. Its entirely windows specific and arch specific.

The purpose here is to run things on the client not provide a service.

**Comment by lxknvlk** [comment]
@TechnikEmpire i have enabled the  Intel inference engine, but completely no performance improvements with it. Could you give a hint? I have enabled the  Intel inference engine like so when doing cmake in opencv/build folder: added -D WITH_INF_ENGINE=ON \
-D ENABLE_CXX11=ON \ params to the cmake command. Then make and sudo make install.

**Comment by TechnikEmpire** [comment]
64 bit? Cause that's not possible. Are you including api transport time in your benchmark?

**Comment by TechnikEmpire** [comment]
Define decent hardware please. Cause I can destroy those benchmarks on a netbook running an Intel atom processor. Basically a calculator.

**Comment by lxknvlk** [comment]
Running on aws instance with Tesla V100 ... , yes 64bit. 

Im using the python script like in the yahoo repo. Im using a ~800kb image to classify.

**Comment by TechnikEmpire** [comment]
Yeah something is wrong there. I think I mentioned not to use python right? There's a performance bug on the yahoo repo all tied to python

Python is great for rapid prototyping if you don't know any better languages. Its not suitable for high performance applications. I don't care who says it is. I cannot offer any more insight on this. These are all issues with properly compiling and executing neural network libraries. I strongly recommend that you follow the c++ examples in opencv's dnn library and also learn to compile opencv with SIMD optimised decoders libraries if you want performance. 

Lastly, using a gpu for this model is a waste of money. Any decently modern CPU can run this network in real time.

**Comment by lxknvlk** [comment]
@TechnikEmpire so the best way is to write my own sript on C++ that uses the inference engine, is that so?

**Comment by TechnikEmpire** [comment]
Yes. Look at my code in nsfw-net (another repo of mine).
